-- MySQL Script generated by MySQL Workbench
-- 11/19/14 23:00:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `name` VARCHAR(45) NOT NULL,
  `monster` VARCHAR(45) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Monster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Monster` (
  `name` VARCHAR(45) NOT NULL,
  `breakable_parts` VARCHAR(45) NULL,
  `carves` VARCHAR(45) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quests` (
  `name` VARCHAR(45) NOT NULL,
  `reward` VARCHAR(45) NULL,
  `Area_name` VARCHAR(45) NOT NULL,
  `Monster_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`, `Area_name`, `Monster_name`),
  INDEX `fk_Quests_Area1_idx` (`Area_name` ASC),
  INDEX `fk_Quests_Monster1_idx` (`Monster_name` ASC),
  CONSTRAINT `fk_Quests_Area1`
    FOREIGN KEY (`Area_name`)
    REFERENCES `mydb`.`Area` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quests_Monster1`
    FOREIGN KEY (`Monster_name`)
    REFERENCES `mydb`.`Monster` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Breakable_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Breakable_parts` (
  `body_part` VARCHAR(45) NOT NULL,
  `Monster_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`body_part`, `Monster_name`),
  INDEX `fk_Breakable_parts_Monster1_idx` (`Monster_name` ASC),
  CONSTRAINT `fk_Breakable_parts_Monster1`
    FOREIGN KEY (`Monster_name`)
    REFERENCES `mydb`.`Monster` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `mydb`.`Elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Elements` (
  `type` VARCHAR(45) NOT NULL,
  `weapon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`weapon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Weapon` (
  `name` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NULL,
  `damage` VARCHAR(45) NULL,
  `sharpness` VARCHAR(45) NULL,
  `Elements_weapon` VARCHAR(45) NOT NULL,
  `carves_needed` VARCHAR(255) NULL,
  PRIMARY KEY (`name`, `Elements_weapon`),
  INDEX `fk_Weapon_Elements_idx` (`Elements_weapon` ASC),
  CONSTRAINT `fk_Weapon_Elements`
    FOREIGN KEY (`Elements_weapon`)
    REFERENCES `mydb`.`Elements` (`weapon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carves` (
  `name` VARCHAR(45) NOT NULL,
  `rarity` VARCHAR(45) NULL,
  `Weapon_name` VARCHAR(45) NOT NULL,
  `Breakable_parts_body_part` VARCHAR(45) NOT NULL,
  `Monster_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`, `Weapon_name`, `Breakable_parts_body_part`, `Monster_name`),
  INDEX `fk_Carves_Weapon1_idx` (`Weapon_name` ASC),
  INDEX `fk_Carves_Breakable_parts1_idx` (`Breakable_parts_body_part` ASC),
  INDEX `fk_Carves_Monster1_idx` (`Monster_name` ASC),
  CONSTRAINT `fk_Carves_Weapon1`
    FOREIGN KEY (`Weapon_name`)
    REFERENCES `mydb`.`Weapon` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carves_Breakable_parts1`
    FOREIGN KEY (`Breakable_parts_body_part`)
    REFERENCES `mydb`.`Breakable_parts` (`body_part`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carves_Monster1`
    FOREIGN KEY (`Monster_name`)
    REFERENCES `mydb`.`Monster` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area_has_Monster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area_has_Monster` (
  `Area_name` VARCHAR(45) NOT NULL,
  `Monster_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Area_name`, `Monster_name`),
  INDEX `fk_Area_has_Monster_Monster1_idx` (`Monster_name` ASC),
  INDEX `fk_Area_has_Monster_Area1_idx` (`Area_name` ASC),
  CONSTRAINT `fk_Area_has_Monster_Area1`
    FOREIGN KEY (`Area_name`)
    REFERENCES `mydb`.`Area` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Area_has_Monster_Monster1`
    FOREIGN KEY (`Monster_name`)
    REFERENCES `mydb`.`Monster` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
